### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ppafm#27]
It would be useful to get ProbeParticle running on Windows. The main user base there would probably be experimentalists who want to use the GUI to get a quick idea of what an AFM image of a molecule would look like. Especially here it would be important to get the GUI working such that you can just one-click launch it from a program icon.

Running the GUI itself in Anaconda works. The main issue seems to be to get the c++-extensions compiled. Supposedly it can be done with MinGW, but I had no success with it.

@yakutovicha says this can also be done with Docker.

might be resolved by #55

**Comment by NikoOinonen** [comment]
To be a bit more specific about my test with MinGW, I did manage to get most of the c++ code compiled into dlls after some tweaks, and got the corresponding Python modules initialized (e.g. GridUtils), but when it got to actually calling the C++ routine, then it crashed with some memory access error. If you know how to do it properly, then I guess you could try, but if we can side-step all of these issues by using a Docker container, then maybe it's not worth the effort.

**Comment by ondrejkrejci** [comment]
I will start a wiki sub-page, how to get a _pip_ on windows in near future. Personally, I've just downloaded a python3.10 from Microsoft store and I had immediately _pip_ in both command lines environments - _cmd_ and _terminal_.

**Comment by ondrejkrejci** [comment]
I will try this thing https://www.pythonguis.com/installation/install-pyqt-windows/ soon (have it here to remember the page)

**Comment by ondrejkrejci** [comment]
Another thing for me: https://docs.conda.io/projects/conda/en/latest/user-guide/install/windows.html

**Comment by yakutovicha** [comment]
@ondrejkrejci, the Docker PR #56 is merged. Please install Docker on a Win machine and try to build and image and run the code there. Thanks!

if it works - feel free to close the PR.

**Comment by ProkopHapala** [comment]
I tried it, but something is wrong 

NOTE: I have no previous experience using docker

```
PS C:\WINDOWS\system32> cd C:\Users\proko\git

PS C:\Users\proko\git> git clone https://github.com/Probe-Particle/ppafm.git
Cloning into 'ppafm'...
remote: Enumerating objects: 6071, done.
remote: Counting objects: 100% (1642/1642), done.
remote: Compressing objects: 100% (585/585), done.
remote: Total 6071 (delta 1291), reused 1169 (delta 1046), pack-reused 4429Receiving objects: 100% (6

Resolving deltas: 100% (4188/4188), done.

PS C:\Users\proko\git> docker build -t ppafm:latest .
[+] Building 0.1s (2/2) FINISHED
 => [internal] load build definition from Dockerfile                                            0.1s
 => => transferring dockerfile: 2B                                                              0.0s
 => [internal] load .dockerignore                                                               0.1s
 => => transferring context: 2B                                                                 0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount3158103203/Dockerfile: no such file or directory
PS C:\Users\proko\git> ls


    Directory: C:\Users\proko\git


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         4/17/2023   1:05 AM                FireCore
d-----         4/25/2023   5:28 PM                ppafm


PS C:\Users\proko\git>
```

**Comment by ProkopHapala** [comment]
NOTE:

I get the same error when I just try to run hellworld container form [Docker documentation](https://docs.docker.com/get-started/run-your-own-container/)


```
PS C:\Users\proko\git> git clone https://github.com/docker/welcome-to-docker
Cloning into 'welcome-to-docker'...
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (6/6), done.
Receiving objects: 100% (94/94), 312.27 KiB | 7.26 MiB/s, done.

Resolving deltas: 100% (44/44), done.
PS C:\Users\proko\git> docker build -t welcome-to-docker .
[+] Building 0.1s (2/2) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                   0.0s
 => => transferring dockerfile: 2B                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                        0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount1730425285/Dockerfile: no such file or directory
PS C:\Users\proko\git>
```

**Comment by yakutovicha** [comment]
@ProkopHapala I think the error message says it doesn't see the `Dockerfile`. You need to enter the `ppafm` folder first.

**Comment by ondrejkrejci** [comment]
@ProkopHapala - I have managed to install Docker through classical download of a package from a desktop and installation. So far so good.
@yakutovicha I have tried to create a ppafm through Docker and got this error:
```
PS C:\Users\krejcio1\WORK\PPAFM\docker_instal> docker build -t ppafm:latest .
[+] Building 177.8s (13/14)                                                                                                                                                                       docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                        0.0s
 => => transferring dockerfile: 868B                                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.10                                                                                                                                             7.0s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                                                                                               0.0s
 => [1/9] FROM docker.io/library/ubuntu:22.10@sha256:e322f4808315c387868a9135beeb11435b5b83130a8599fd7d0014452c34f489                                                                                      12.2s
 => => resolve docker.io/library/ubuntu:22.10@sha256:e322f4808315c387868a9135beeb11435b5b83130a8599fd7d0014452c34f489                                                                                       0.0s
 => => sha256:692eb4a905c074054e0a35d647671f0e32ed150d15b23fd7bc745cfb2fdeddbd 2.30kB / 2.30kB                                                                                                              0.0s
 => => sha256:3ad6ea492c35ef48892b4587449510d372516d5969073eeaa6601a380e861c57 26.70MB / 26.70MB                                                                                                            9.8s
 => => sha256:e322f4808315c387868a9135beeb11435b5b83130a8599fd7d0014452c34f489 1.13kB / 1.13kB                                                                                                              0.0s
 => => sha256:d36481db487c935436420cc4b705db8c81eec3872085ebd27963b775695fbe24 424B / 424B                                                                                                                  0.0s
 => => extracting sha256:3ad6ea492c35ef48892b4587449510d372516d5969073eeaa6601a380e861c57                                                                                                                   2.1s
 => [internal] load build context                                                                                                                                                                           0.1s
 => => transferring context: 18.67kB                                                                                                                                                                        0.1s
 => [2/9] RUN apt-get update --yes &&                           apt-get install --yes --no-install-recommends     build-essential                                   python3                               146.4s
 => [3/9] RUN useradd -ms /bin/bash ppafm-user                                                                                                                                                              0.6s
 => [4/9] RUN mkdir /exec && chown ppafm-user:ppafm-user /exec                                                                                                                                              0.6s
 => [5/9] WORKDIR /home/ppafm-user                                                                                                                                                                          0.0s
 => [6/9] RUN pip install --upgrade --user pip && pip cache purge                                                                                                                                           5.6s
 => [7/9] COPY --chown=ppafm-user:ppafm-user ./ ppafm                                                                                                                                                       0.0s
 => ERROR [8/9] RUN pip install -e ppafm/ && pip cache purge                                                                                                                                                5.1s
------
 > [8/9] RUN pip install -e ppafm/ && pip cache purge:
0.881 Defaulting to user installation because normal site-packages is not writeable
0.927 Obtaining file:///home/ppafm-user/ppafm
0.933   Installing build dependencies: started
4.674   Installing build dependencies: finished with status 'done'
4.676   Checking if build backend supports build_editable: started
4.822   Checking if build backend supports build_editable: finished with status 'done'
4.824   Getting requirements to build editable: started
4.979   Getting requirements to build editable: finished with status 'error'
4.991   error: subprocess-exited-with-error
4.991
4.991   × Getting requirements to build editable did not run successfully.
4.991   │ exit code: 1
4.991   ╰─> [47 lines of output]
4.991       /tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/config/pyprojecttoml.py:66: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
4.991         config = read_configuration(filepath, True, ignore_option_errors, dist)
4.991       Traceback (most recent call last):
4.991         File "/home/ppafm-user/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
4.991           main()
4.991         File "/home/ppafm-user/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
4.991           json_out['return_val'] = hook(**hook_input['kwargs'])
4.991         File "/home/ppafm-user/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
4.991           return hook(config_settings)
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 450, in get_requires_for_build_editable
4.991           return self.get_requires_for_build_wheel(config_settings)
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
4.991           return self._get_build_requires(config_settings, requirements=['wheel'])
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 323, in _get_build_requires
4.991           self.run_setup()
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 338, in run_setup
4.991           exec(code, locals())
4.991         File "<string>", line 38, in <module>
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 107, in setup
4.991           return distutils.core.setup(**attrs)
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 159, in setup
4.991           dist.parse_config_files()
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/dist.py", line 898, in parse_config_files
4.991           pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/config/pyprojecttoml.py", line 66, in apply_configuration
4.991           config = read_configuration(filepath, True, ignore_option_errors, dist)
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/config/pyprojecttoml.py", line 132, in read_configuration
4.991           return expand_configuration(asdict, root_dir, ignore_option_errors, dist)
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/config/pyprojecttoml.py", line 157, in expand_configuration
4.991           return _ConfigExpander(config, root_dir, ignore_option_errors, dist).expand()
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/config/pyprojecttoml.py", line 205, in expand
4.991           self._expand_all_dynamic(dist, package_dir)
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/config/pyprojecttoml.py", line 250, in _expand_all_dynamic
4.991           version=self._obtain_version(dist, package_dir),
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/config/pyprojecttoml.py", line 299, in _obtain_version
4.991           return _expand.version(self._obtain(dist, "version", package_dir))
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/config/pyprojecttoml.py", line 288, in _obtain
4.991           return self._expand_directive(
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/config/pyprojecttoml.py", line 282, in _expand_directive
4.991           return _expand.read_attr(directive["attr"], package_dir, root_dir)
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/config/expand.py", line 188, in read_attr
4.991           spec = _find_spec(module_name, path)
4.991         File "/tmp/pip-build-env-kylqystx/overlay/local/lib/python3.10/dist-packages/setuptools/config/expand.py", line 200, in _find_spec
4.991           spec = spec or importlib.util.find_spec(module_name)
4.991         File "/usr/lib/python3.10/importlib/util.py", line 94, in find_spec
4.991           parent = __import__(parent_name, fromlist=['__path__'])
4.991       ModuleNotFoundError: No module named 'ppafm'
4.991       [end of output]
4.991
4.991   note: This error originates from a subprocess, and is likely not a problem with pip.
4.995 error: subprocess-exited-with-error
4.995
4.995 × Getting requirements to build editable did not run successfully.
4.995 │ exit code: 1
4.995 ╰─> See above for output.
4.995
4.995 note: This error originates from a subprocess, and is likely not a problem with pip.
------
Dockerfile:25
--------------------
  23 |     COPY --chown=ppafm-user:ppafm-user ./ ppafm
  24 |
  25 | >>> RUN pip install -e ppafm/ && pip cache purge
  26 |
  27 |
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -e ppafm/ && pip cache purge" did not complete successfully: exit code: 1
```

Generally speaking I would suggest to use Anaconda on Windows machines for sure - it was super easy to setup and it is working perfectly for me.

**Comment by yakutovicha** [comment]
@ondrejkrejci, can you show me the content of your `C:\Users\krejcio1\WORK\PPAFM\docker_instal` folder? I just managed to build it on my colleague's windows machine, so I am surprised it didn't work for you.

**Comment by ondrejkrejci** [comment]
On Monday, I have holiday today.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by NikoOinonen** [comment]
I managed to run Docker under Windows when testing #181. The only quirk I found on Windows is that the way to invoke the docker image is different in CMD and in PowerShell, which I added to the [wiki page](https://github.com/Probe-Particle/ppafm/wiki/Additional-installation-instructions#other-installation-options).

**Comment by yakutovicha** [comment]
Thanks, @NikoOinonen - I think we can safely close the issue. Enough ways to run `ppafm` on different OS have been added 👍

**Comment by ondrejkrejci** [comment]
@yakutovicha - OK, it seems that my docker environment is broken, since I was not able to build even aiida on it. No idea where this is comming from, but I have a different way, how to run it on windows, thus I am happy, no need to reopen this issue.
@NikoOinonen - One thing that I missing on the [wiki page](https://github.com/Probe-Particle/ppafm/wiki/Additional-installation-instructions#other-installation-options) - It is absolutuly not clear if it should be run from a downloaded ppafm folder (I suspect) or from an empty folder ... (Just a simple note on the wiki is enough, no need to reopen anything).

**Comment by NikoOinonen** [comment]
@ondrejkrejci I assume you meant running with docker. I added a small note there on the [wiki page](https://github.com/Probe-Particle/ppafm/wiki/Additional-installation-instructions#docker-container) that you can replace the lines in the `run.sh` scripts with the docker commands.

**Comment by ondrejkrejci** [comment]
@NikoOinonen: I meant in the beginning, of the docker container. If you think of some Win user with no knowledge of shell/terminal before I do not think that what is written can give someone enough:

> [Docker](https://docs.docker.com/get-docker/) is a platform-independent way of running the code.
> After installing Docker on your system, here are the steps to build and run the ppafm Docker container:
> Build the image.
> docker build -t ppafm:latest .

Especially the last line implicitely mean that you navigate to folder (empty folder or folder with downloaded ppafm? which is unzipper -- really thinking about the mouse using guys) and start terminal/PowerShell in that folder and then run that command. Please could you make it more clear?

Unfortunately my Aalto laptop is super tough to be working properly on Windows, so I cannot update this part of the wiki, as I cannot test it. I have added some additional instructions about building the code, so it is more clear at least from my point of view. Feel free to adapt.

**Comment by NikoOinonen** [comment]
@ondrejkrejci I quickly added some more details to the wiki page. I not sure if Docker is really the best platform for a complete beginner to the terminal. I think it's more used for creating consistent development environments or server deployments and stuff.
