### ISSUE TITLE
Fix Axes.ArtistList usage in GUIWidgets

### ISSUE THREAD

**Issue by NikoOinonen** [Probe-Particle/ppafm#95]
This line in GUIWidgets throws an error on matplotlib>=3.7.0: https://github.com/Probe-Particle/ppafm/blob/d559640e41f551d9e97a7bc958b80c41cd484dd1/ppafm/GUIWidgets.py#L90

```
Traceback (most recent call last):
  File "/home/work/git/PPMOpenCL/GUI/./ppm-gui", line 585, in updateDataView
    self.figCan.plotSlice(data, -1, title=title, points=self.df_points, cbar_range=cbar_range,
  File "/home/work/git/PPMOpenCL/ppafm/GUIWidgets.py", line 90, in plotSlice
    self.axes.lines.clear()
AttributeError: 'ArtistList' object has no attribute 'clear'
```

This is due to a deprecation: https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.7.0.html#modification-of-axes-children-sublists

Matplotlib version is blocked at 3.6.3 until this is resolved.

**Comment by NikoOinonen** [comment]
I'll start working on this now.
